
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jayita
 */
public class Frame3F extends javax.swing.JFrame {

    /**
     * Creates new form Frame3F
     */
    public Frame3F() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        profession = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        professionLB = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        employed = new javax.swing.JRadioButton();
        unemployed = new javax.swing.JRadioButton();
        pass12 = new javax.swing.JCheckBox();
        college = new javax.swing.JCheckBox();
        tf3 = new javax.swing.JLabel();
        salaryLB = new javax.swing.JLabel();
        tf4 = new javax.swing.JLabel();
        pass10 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        tf7 = new javax.swing.JLabel();
        tf6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jButton3.setText("RESET");

        jButton4.setText("NEXT>>");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Bebas", 0, 36)); // NOI18N
        jLabel4.setText("CENSUS   OF   INDIA - 3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 340, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/census-of-india-2011-logo.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel5.setText("Job Status :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 326, 154, -1));

        profession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professionActionPerformed(evt);
            }
        });
        getContentPane().add(profession, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 363, 186, -1));

        jLabel1.setText("Educational Qualifications :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 228, 154, -1));

        professionLB.setText("Profession :");
        getContentPane().add(professionLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 366, 154, -1));

        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 389, 186, -1));

        buttonGroup1.add(employed);
        employed.setText("Employed");
        employed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employedActionPerformed(evt);
            }
        });
        getContentPane().add(employed, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 322, -1, -1));

        buttonGroup1.add(unemployed);
        unemployed.setText("Unemployed");
        unemployed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unemployedActionPerformed(evt);
            }
        });
        getContentPane().add(unemployed, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 322, -1, -1));

        pass12.setText("12th Pass");
        getContentPane().add(pass12, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 250, 186, -1));

        college.setText("College Graduate");
        college.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeActionPerformed(evt);
            }
        });
        getContentPane().add(college, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 281, 186, -1));

        tf3.setForeground(new java.awt.Color(255, 0, 0));
        tf3.setText("Fill this!");
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 366, -1, -1));

        salaryLB.setText("Monthly Salary :");
        getContentPane().add(salaryLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 392, -1, -1));

        tf4.setForeground(new java.awt.Color(255, 0, 0));
        tf4.setText("Fill this!");
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 392, -1, -1));

        pass10.setText("10th Pass");
        getContentPane().add(pass10, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 224, 127, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 136, -1, -1));

        jButton9.setText("RESET");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 73, -1));

        jButton10.setText("SUBMIT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        tf7.setForeground(new java.awt.Color(255, 0, 0));
        tf7.setText("Choose one !");
        getContentPane().add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        tf6.setForeground(new java.awt.Color(255, 0, 0));
        tf6.setText("Choose one !");
        getContentPane().add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slider-3.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-710, 0, 1200, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void professionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professionActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void employedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employedActionPerformed
        profession.setVisible(true);
        professionLB.setVisible(true);
        salary.setVisible(true);
        salaryLB.setVisible(true);
    }//GEN-LAST:event_employedActionPerformed

    private void unemployedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unemployedActionPerformed
        profession.setVisible(false);
        professionLB.setVisible(false);
        salary.setVisible(false);
        salaryLB.setVisible(false);
        profession.setText(null);
        salary.setText(null);
    }//GEN-LAST:event_unemployedActionPerformed

    private void collegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegeActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

try
        {
        int x = 0;
if (pass10.isSelected() == false && pass12.isSelected() == false && college.isSelected() == false)  {
    x++;
    tf6.setVisible(true);
    }
if (employed.isSelected() == false && unemployed.isSelected() == false)  {
    x++;
    tf7.setVisible(true);
    }
if (employed.isSelected())  {
    if (profession.getText().equals(""))  {
        x++;
        tf3.setVisible(true);
        }
    if (salary.getText().equals(""))  {
        x++;
        tf4.setVisible(true);
        }
}
String pas10="N/A";
String pas12="N/A";
String colege="N/A";
String Jobb="N/A";
if(pass10.isSelected())
{
    pas10="Yes";
}
if(pass12.isSelected())
{
    pas12="Yes";
}
if(college.isSelected())
{
    colege="Yes";
}
if(employed.isSelected())
{
    Jobb="Yes";
}
String pro=profession.getText();
String sal=salary.getText();
if(pro.equals(""))
{
    pro="N/A";
}
if(sal.equals(""))
{
    sal="N/A";
}


            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)
                    DriverManager.getConnection ("jdbc:mysql://localhost:3306/hoho", "root", "jayita27");
            
            Statement stmt=(Statement) con.createStatement();
            
            String query="INSERT INTO frame3 VALUES ('"+pas10+"','"+pas12+"','"+colege+"','"
                +Jobb+ "','"+pro+"','"+sal+"');";
            
            stmt.executeUpdate(query);
            
            
        
       if (x == 0)
{
ThanksF Q=new ThanksF();
Q.setVisible(true);
this.setVisible(false);}
       
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        pass10.setSelected(false);
pass12.setSelected(false);
college.setSelected(false);
profession.setText(null);
salary.setText(null);
profession.setVisible(false);
professionLB.setVisible(false);
salary.setVisible(false);
salaryLB.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:tf1.setVisible(false);
tf7.setVisible(false);
tf6.setVisible(false);
tf3.setVisible(false);
tf4.setVisible(false);
salary.setVisible(false);
salaryLB.setVisible(false);
profession.setVisible(false);
professionLB.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame3F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame3F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame3F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame3F.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame3F().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox college;
    private javax.swing.JRadioButton employed;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox pass10;
    private javax.swing.JCheckBox pass12;
    private javax.swing.JTextField profession;
    private javax.swing.JLabel professionLB;
    private javax.swing.JTextField salary;
    private javax.swing.JLabel salaryLB;
    private javax.swing.JLabel tf3;
    private javax.swing.JLabel tf4;
    private javax.swing.JLabel tf6;
    private javax.swing.JLabel tf7;
    private javax.swing.JRadioButton unemployed;
    // End of variables declaration//GEN-END:variables
}
