import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jayita
 */
public class FrameF extends javax.swing.JFrame {

    /**
     * Creates new form FrameF
     */
    public FrameF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adrs = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        adrstype = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        phn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        aad = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("Fill this!");

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Fill this!");

        lbl5.setForeground(new java.awt.Color(255, 0, 0));
        lbl5.setText("Fill this!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 302, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bebas", 0, 36)); // NOI18N
        jLabel4.setText("CENSUS   OF   INDIA - 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 340, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/census-of-india-2011-logo.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("This is your:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 100, 14));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("First Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 100, 14));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Last Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, 14));
        getContentPane().add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 230, -1));
        getContentPane().add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 230, -1));
        getContentPane().add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 230, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("E-Mail ID:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 100, 14));

        adrs.setColumns(20);
        adrs.setRows(5);
        jScrollPane1.setViewportView(adrs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 220, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Address:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 100, 14));

        adrstype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Permanent Address", "Temporary Address" }));
        getContentPane().add(adrstype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Phone Number:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 100, 14));
        getContentPane().add(phn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 230, -1));

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 73, -1));

        jButton3.setText("INSERT RECORD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, -1, -1));

        jLabel12.setText("Aadhar No:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 20));
        getContentPane().add(aad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 230, -1));

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 70, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slider-3.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-770, 0, 1230, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fn.setText("");
        ln.setText("");
        aad.setText("");
        adrs.setText("");
        phn.setText("");
        t9.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String first=fn.getText();
        String last=ln.getText();
        
        String aadhar=aad.getText();
        String ad=adrs.getText();
        String mail=t9.getText();
        int i=adrstype.getSelectedIndex();
        String adtype="";
        if (i==0) adtype="Permanent";
        else{}
        if (i==1) adtype="Temporary";
        else{
        
        }
        String ph=phn.getText();
        if(first.equals("")||last.equals("")||ad.equals("")||aadhar.equals("")||mail.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please fill in all the details");
        }
        else {
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)
                    DriverManager.getConnection ("jdbc:mysql://localhost:3306/hoho", "root", "jayita27");
            
            Statement stmt=(Statement) con.createStatement();
            
            String query="INSERT INTO frame1 VALUES ('"+first+" ',' "+last+" ', '"+ad+"','"
                    +adtype+ "', ' "+ph+"','"+aadhar+"','"+mail+"');";
            
            stmt.executeUpdate(query);
            
            fn.setText("");
        ln.setText("");
        
        adrs.setText("");
        phn.setText("");
        t9.setText("");
        
        JOptionPane.showMessageDialog(this, "Successfully entered data!");
        
        String msg=aad.getText();
        new Frame2F(msg).setVisible(true);
        this.setVisible(false);
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        LoginF V= new LoginF();
            V.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aad;
    private javax.swing.JTextArea adrs;
    private javax.swing.JComboBox<String> adrstype;
    private javax.swing.JTextField fn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl5;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField phn;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
